## Name:karthik konar
## Sap Id:70611019018
## Roll No:A002Â¶

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Question 1.csv')

In [5]:
df['Revised_Year']=df['Year']+10

In [6]:
df['Revised_Year'].head()

0    1970
1    1971
2    1972
3    1973
4    1974
Name: Revised_Year, dtype: int64

In [9]:
df.groupby((df.Year//10)*10).sum()

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft,Revised_Year
Year,,,,,,,,,,,,,
1960,19645,1915053175,49295900,4134930,45160900,106180,236720,1633510,2158520,13321100,26547700,5292100,19745
1970,19745,2121193298,100991600,9607930,91383800,192230,554570,4159020,4702120,28486000,53157800,9739900,19845
1980,19845,2371370069,131123369,14074328,117048900,206439,865639,5383109,7619130,33073494,72040253,11935411,19945
1990,19945,2612825258,136582146,17527048,119053499,211664,998827,5748930,10568963,26750015,77679366,14624418,20045
2000,20045,2947969117,115012044,13968056,100944369,163068,922499,4230366,8652124,21565176,67970291,11412834,20145
2010,10060,1570146307,50167967,6072017,44095950,72867,421059,1749809,3764142,10125170,30401698,3569080,10110